#!/bin/zsh
if [[ -e tags ]]; then
    echo '----------'
    echo 'UPDATE ctags'
    echo '----------'

    ctags -R 2>&1 /dev/null
fi

if [[ -e GTAGS ]]; then
    echo '----------'
    echo 'UPDATE gtags'
    echo '----------'

    gtags --incremental 2>&1 > /dev/null
fi

exit 1
